name: Bug Report
description: Report a bug in the application.
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Description
        Please describe the bug you encountered.

  - type: input
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      placeholder: Step 1, Step 2, Step 3...

  - type: textarea
    id: expected-results
    attributes:
      label: Expected results
      placeholder: What you expected to happen...
