blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://example.com/support
    about: Get help from our support team
templates:
  - title: Bug Report
    description: Use this template to report a bug.
    file: bug_report.yml
  - title: Feature Request
    description: Use this template to suggest a new feature.
    file: feature_request.yml
