name: Bug report 🐛
description: Report a bug in our website to help us improve
title: '[Bug]: '
labels: 'type: bug 🐛'

body:
  - type: markdown
    attributes:
      value: '## Welcome!'
  - type: markdown
    attributes:
      value:
        Thanks for taking the time to report report a bug in our website to help
        us improve.

  - type: input
    id: system
    attributes:
      label: System
      description: 'What operating system are you using?'
      placeholder: macOS
    validations:
      required: false
